### ISSUE TITLE
Update superagent

### ISSUE THREAD

**Issue by aaronschachter** [mbasso/react-http-request#7]
Superagent could use an update:

├─┬ react-http-request@1.0.4
│ └─┬ superagent@1.7.2
│   └── mime@1.3.4

**Comment by mbasso** [comment]
Hi @aaronschachter,
Thank you for opening this issue 😄
Yeah, I think that we should update it. I'll check if there are breaking changes to consider.
I'm a little bit busy at the moment but I'll do it as soon as possible!

**Comment by ceastman-ibm** [comment]
@mbasso as part of this can you upgrade to at least superagent@3.8.1 so it resolves all issues reported by snyk.io?

https://www.npmjs.com/package/superagent#upgrading-from-previous-versions

**Comment by mbasso** [comment]
Hi @ceastman-ibm,
I've started working on it, I'll create a new branch and publish an alpha version this night or tomorrow

**Comment by mbasso** [comment]
I've just created a new branch and published a new version with the `next` tag.
The library now uses `superagent@^4.1.0`, please try it out and let me know if I can publish it with the `latest` tag 😄 
Just run:

```bash
npm install react-http-request@next
```

Please note that this is a major update since the new versions of `superagent` have dropped the support for node < 6 and you have to polyfill the `Promise` object in Internet Explorer

**Comment by mbasso** [comment]
Just published `react-http-request@2.0.0` 🎉
